# Generated by Django 5.2.7 on 2026-01-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korisnik_ime', models.CharField(max_length=50)),
                ('korisnik_datum_rodenja', models.DateField()),
                ('korisnik_id', models.IntegerField()),
                ('korisnik_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
