# Generated by Django 5.2.7 on 2026-02-19 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trener_ime', models.CharField(max_length=50)),
                ('trener_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Trening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trening_ime', models.CharField(max_length=20)),
                ('trening_vrsta', models.CharField(choices=[('kardio', 'Kardio'), ('snaga', 'Snaga'), ('funkcionalni', 'Funkcionalni'), ('HIIT', 'hiit'), ('yoga', 'Yoga')], max_length=20)),
                ('trening_opis', models.TextField()),
                ('trening_termin', models.DateTimeField(default=django.utils.timezone.now)),
                ('trening_trener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trener')),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korisnik_ime', models.CharField(max_length=50)),
                ('korisnik_datum_rodenja', models.DateField()),
                ('korisnik_mail', models.EmailField(max_length=254)),
                ('korisnik_trening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trening')),
            ],
        ),
    ]
