# Generated by Django 5.2.7 on 2026-01-25 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trener_ime', models.CharField(max_length=50)),
                ('trener_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='korisnik_id',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Trening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trening_ime', models.CharField(max_length=20)),
                ('trening_vrsta', models.CharField(max_length=20)),
                ('trening_opis', models.TextField()),
                ('trening_trener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trener')),
            ],
        ),
    ]
