# Generated by Django 5.2.7 on 2026-01-28 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_trener_alter_korisnik_korisnik_id_trening'),
    ]

    operations = [
        migrations.AddField(
            model_name='trening',
            name='trening_termin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
