# Generated by Django 5.2.7 on 2026-01-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_trening_trening_termin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='korisnik_id',
        ),
        migrations.RemoveField(
            model_name='trener',
            name='trener_id',
        ),
    ]
